export const GET_STATS_REQUEST = 'GET_STATS_REQUEST'
export const GET_STATS_FAIL = 'GET_STATS_FAIL'
export const GET_STATS_SUCCESS = 'GET_STATS_SUCCESS'
export const SET_STATS = 'SET_STATS'

export const GET_POKEMON_REQUEST = 'GET_POKEMON_REQUEST'
export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS'
export const GET_POKEMON_FAIL = 'GET_POKEMON_FAIL'
export const SET_POKEMON = 'SET_POKEMON'
